
version: 2

restore_cache: &restore_cache
  restore_cache:
    keys:
      - jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - builds-{{ .Revision }}
      - app-builds-{{ .Revision }}
jobs:
  build:
    working_directory: ~/norimaki
    docker:
      - image: cimg/android:2022.09
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
      - run:
          name: Build
          command: ./gradlew assembleDebugUnitTest
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - save_cache:
          paths:
            - ~/norimaki/build
          key: builds-{{ .Revision }}
      - save_cache:
          paths:
            - ~/norimaki/app/build